/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/workspace/skamansam.github.io/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3d75f994",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d75f994").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-25ed5e18",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25ed5e18").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-06532fa2",
    path: "/authors/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06532fa2").then(next)
    },
  },
  {
    path: "/authors/index.html",
    redirect: "/authors/"
  },
  {
    name: "v-625996b2",
    path: "/authors/skamansam.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-625996b2").then(next)
    },
  },
  {
    name: "v-595cb904",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-595cb904").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-e001bbf2",
    path: "/categories/javascript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e001bbf2").then(next)
    },
  },
  {
    name: "v-dc94ec1e",
    path: "/categories/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dc94ec1e").then(next)
    },
  },
  {
    name: "v-83a40ec6",
    path: "/categories/open-source.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-83a40ec6").then(next)
    },
  },
  {
    name: "v-324b4a72",
    path: "/categories/perl.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-324b4a72").then(next)
    },
  },
  {
    name: "v-4f2f5032",
    path: "/categories/personal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f2f5032").then(next)
    },
  },
  {
    name: "v-73288cc9",
    path: "/categories/portfolio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73288cc9").then(next)
    },
  },
  {
    name: "v-688a7667",
    path: "/categories/programming.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-688a7667").then(next)
    },
  },
  {
    name: "v-64d324a7",
    path: "/categories/ruby.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64d324a7").then(next)
    },
  },
  {
    name: "v-19db9e7b",
    path: "/categories/vuejs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19db9e7b").then(next)
    },
  },
  {
    name: "v-71fdacd6",
    path: "/categories/web-development.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71fdacd6").then(next)
    },
  },
  {
    name: "v-4968f81c",
    path: "/contact/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4968f81c").then(next)
    },
  },
  {
    path: "/contact/index.html",
    redirect: "/contact/"
  },
  {
    name: "v-7caa0a27",
    path: "/posts/2008-03-05-welcome-to-my-blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-7caa0a27").then(next)
    },
  },
  {
    name: "v-0ef6a32a",
    path: "/posts/2008-04-23-accepted-into-google-summer-of-code.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-0ef6a32a").then(next)
    },
  },
  {
    name: "v-ab6f9872",
    path: "/posts/2008-05-09-wxcpan-skeleton-code.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-ab6f9872").then(next)
    },
  },
  {
    name: "v-4d6dbde9",
    path: "/posts/2008-05-13-wxcpan-going-well.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-4d6dbde9").then(next)
    },
  },
  {
    name: "v-4418ef07",
    path: "/posts/2008-05-24-gsoc-day-0-equals-hit-the-ground-running.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-4418ef07").then(next)
    },
  },
  {
    name: "v-d77d7ebe",
    path: "/posts/2008-08-05-my-baby.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-d77d7ebe").then(next)
    },
  },
  {
    name: "v-09948067",
    path: "/posts/2008-08-05-my-baby2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-09948067").then(next)
    },
  },
  {
    name: "v-1a4255b2",
    path: "/posts/2008-08-05-my-bartender-mark.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-1a4255b2").then(next)
    },
  },
  {
    name: "v-6d1ef847",
    path: "/posts/2008-08-07-al-at-werk-again.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-6d1ef847").then(next)
    },
  },
  {
    name: "v-01fdfde7",
    path: "/posts/2008-08-07-al-at-werk.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-01fdfde7").then(next)
    },
  },
  {
    name: "v-3cceb24e",
    path: "/posts/2009-01-08-webfx-at-uncg.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-3cceb24e").then(next)
    },
  },
  {
    name: "v-91e81f56",
    path: "/posts/2009-02-02-installing-gentoo-2008-in-qemu-suns-virtualbox-on-fedora-10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-91e81f56").then(next)
    },
  },
  {
    name: "v-42a1e782",
    path: "/posts/2009-02-09-drop-down-menu-with-css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-42a1e782").then(next)
    },
  },
  {
    name: "v-aba30b82",
    path: "/posts/2009-02-14-installing-aptana-in-fedora-eclipse.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-aba30b82").then(next)
    },
  },
  {
    name: "v-bf119fe2",
    path: "/posts/2009-03-11-building-chromium-on-fedora-10-x86-64.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-bf119fe2").then(next)
    },
  },
  {
    name: "v-2915d3f5",
    path: "/posts/2009-03-21-windows-vs-linux-on-msi-gx700.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-2915d3f5").then(next)
    },
  },
  {
    name: "v-0702ed76",
    path: "/posts/2009-04-01-jquery-style-sheet-css-switcher.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-0702ed76").then(next)
    },
  },
  {
    name: "v-4cee78b2",
    path: "/posts/2009-04-02-building-enlightenment-e17-on-fedora-10-x86-64.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-4cee78b2").then(next)
    },
  },
  {
    name: "v-15e8dc72",
    path: "/posts/2009-04-02-google-summer-of-code-2009-project-ideas.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-15e8dc72").then(next)
    },
  },
  {
    name: "v-4b934e93",
    path: "/posts/2009-05-10-tetex-for-puppy-linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-4b934e93").then(next)
    },
  },
  {
    name: "v-68a02f67",
    path: "/posts/2009-05-29-fun-with-numbers.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-68a02f67").then(next)
    },
  },
  {
    name: "v-6913dd53",
    path: "/posts/2009-06-15-how-to-repair-images-with-imagemagick.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-6913dd53").then(next)
    },
  },
  {
    name: "v-01095047",
    path: "/posts/2009-07-31-new-theme-under-construction-dot-dot-dot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-01095047").then(next)
    },
  },
  {
    name: "v-65bf4247",
    path: "/posts/2010-06-02-teaching-computer-science-in-a-web-browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-65bf4247").then(next)
    },
  },
  {
    name: "v-33a34607",
    path: "/posts/2010-06-15-teaching-computer-science-in-a-web-browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-33a34607").then(next)
    },
  },
  {
    name: "v-d9c5dd32",
    path: "/posts/2010-07-28-tango-icons-save-all.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-d9c5dd32").then(next)
    },
  },
  {
    name: "v-24cf8bc7",
    path: "/posts/2011-03-06-jquery-themeswitchertool-working-version.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-24cf8bc7").then(next)
    },
  },
  {
    name: "v-447503a7",
    path: "/posts/2012-02-04-how-to-keep-your-linux-always-on-in-a-dual-boot-system.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-447503a7").then(next)
    },
  },
  {
    name: "v-2e4394a7",
    path: "/posts/2012-05-25-inline-input-fields-with-mnimal-jquery.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-2e4394a7").then(next)
    },
  },
  {
    name: "v-2f1e7027",
    path: "/posts/2016-08-30-moved-to-octopress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-2f1e7027").then(next)
    },
  },
  {
    name: "v-57771753",
    path: "/posts/2016-09-14-data-migrations-and-you.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-57771753").then(next)
    },
  },
  {
    name: "v-5bb6e9e8",
    path: "/posts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bb6e9e8").then(next)
    },
  },
  {
    path: "/posts/index.html",
    redirect: "/posts/"
  },
  {
    name: "v-032c5945",
    path: "/unpublished/2009-05-29-how-to-build-a-dynamic-web-site-with-simple-server-technologies.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-032c5945").then(next)
    },
  },
  {
    name: "v-4feec42a",
    path: "/unpublished/2012-08-31-simple-rails-development-part-ii-core-gedit-plugins.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-4feec42a").then(next)
    },
  },
  {
    name: "v-5d2da6f1",
    path: "/unpublished/2016-09-06-dynamic-models-in-rails-3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-5d2da6f1").then(next)
    },
  },
  {
    name: "v-780ca033",
    path: "/unpublished/2016-09-06-firefox-add-ons-i-cant-live-without.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-780ca033").then(next)
    },
  },
  {
    name: "v-70a92b5f",
    path: "/unpublished/2016-09-06-installing-amaya-on-fedora-10-64bit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-70a92b5f").then(next)
    },
  },
  {
    name: "v-7b888ce7",
    path: "/unpublished/2016-09-06-top-linux-apps-i-cant-live-without.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-7b888ce7").then(next)
    },
  },
  {
    name: "v-0f9630c8",
    path: "/unpublished/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f9630c8").then(next)
    },
  },
  {
    path: "/unpublished/index.html",
    redirect: "/unpublished/"
  },
  {
    name: "v-a7d683b2",
    path: "/posts/2012-08-30-simple-rails-development-part-i-gedit-click-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-a7d683b2").then(next)
    },
  },
  {
    name: "v-133acdb2",
    path: "/posts/2013-04-10-building-a-unified-time-select-field.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-133acdb2").then(next)
    },
  },
  {
    name: "v-76afa00a",
    path: "/posts/2013-04-23-cookie-detection-in-rails-3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("post", "v-76afa00a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]