/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Rude Boy Enterprises",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "http-equiv": "x-ua-compatible",
        "content": "ie=edge"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-title",
        "content": "Rude Boy Enterprises"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "MY COLOR THEME"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-navbutton-color",
        "content": "#00ff00"
      }
    ],
    [
      "meta",
      {
        "name": "mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black-translucent"
      }
    ],
    [
      "meta",
      {
        "name": "coverage",
        "content": "WorldWide"
      }
    ],
    [
      "meta",
      {
        "name": "rating",
        "content": "general"
      }
    ],
    [
      "meta",
      {
        "name": "robots",
        "content": "index,follow"
      }
    ],
    [
      "meta",
      {
        "name": "googlebot",
        "content": "index,follow"
      }
    ],
    [
      "meta",
      {
        "name": "application-name",
        "content": "Rude Boy Enterprises"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#00ff00"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-config",
        "content": "/browserconfig.xml"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-square70x70logo",
        "content": "/favicon/ms-icon-70x70.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/favicon/ms-icon-144x144.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-square150x150logo",
        "content": "/favicon/mstile-150x150.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-wide310x150logo",
        "content": "/favicon/ms-icon-310x310.png"
      }
    ],
    [
      "meta",
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      }
    ],
    [
      "meta",
      {
        "name": "twitter:site",
        "content": "@skamansam"
      }
    ],
    [
      "meta",
      {
        "property": "fb:app_id",
        "content": "MY FACEBOOK APP ID"
      }
    ],
    [
      "meta",
      {
        "property": "og:type",
        "content": "website"
      }
    ],
    [
      "meta",
      {
        "property": "og:site_name",
        "content": "MY SITE NAME"
      }
    ],
    [
      "meta",
      {
        "property": "og:image:height",
        "content": "1200"
      }
    ],
    [
      "meta",
      {
        "property": "og:image:width",
        "content": "360"
      }
    ],
    [
      "meta",
      {
        "property": "og:image:type",
        "content": "image/png"
      }
    ],
    [
      "meta",
      {
        "name": "google-site-verification",
        "content": "MY VERIFICATION KEY"
      }
    ],
    [
      "meta",
      {
        "name": "msvalidate.01",
        "content": "MY VERIFICATION KEY"
      }
    ],
    [
      "meta",
      {
        "name": "yandex-verification",
        "content": "MY VERIFICATION KEY"
      }
    ],
    [
      "link",
      {
        "rel": "publisher",
        "href": "MY URL GOOGLE PLUS"
      }
    ],
    [
      "link",
      {
        "rel": "author",
        "href": "MY URL GOOGLE PLUS"
      }
    ],
    [
      "link",
      {
        "rel": "author",
        "href": "/humans.txt"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "sizes": "57x57",
        "href": "/favicon/apple-icon-57x57.png"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "sizes": "60x60",
        "href": "/favicon/apple-icon-60x60.png"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "sizes": "72x72",
        "href": "/favicon/apple-icon-72x72.png"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "sizes": "76x76",
        "href": "/favicon/apple-icon-76x76.png"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "sizes": "114x114",
        "href": "/favicon/apple-icon-114x114.png"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "sizes": "120x120",
        "href": "/favicon/apple-icon-120x120.png"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "sizes": "144x144",
        "href": "/favicon/apple-icon-144x144.png"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "sizes": "152x152",
        "href": "/favicon/apple-icon-152x152.png"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "sizes": "180x180",
        "href": "/favicon/apple-icon-180x180.png"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "type": "image/png",
        "href": "/favicon/android-icon-192x192.png",
        "sizes": "192x192"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "type": "image/png",
        "href": "/favicon/favicon-96x96.png",
        "sizes": "96x96"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "type": "image/png",
        "href": "/favicon/favicon-32x32.png",
        "sizes": "32x32"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "type": "image/png",
        "href": "/favicon/favicon-16x16.png",
        "sizes": "16x16"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/favicon/safari-pinned-tab.svg",
        "color": "#ff5733"
      }
    ],
    [
      "link",
      {
        "rel": "shortcut icon",
        "href": "/favicon/favicon.ico"
      }
    ],
    [
      "link",
      {
        "rel": "alternate",
        "href": "https://MY_DOMAIN.COM/",
        "hreflang": "en"
      }
    ],
    [
      "link",
      {
        "rel": "alternate",
        "href": "https://MY_DOMAIN.COM/pt/",
        "hreflang": "pt"
      }
    ],
    [
      "link",
      {
        "rel": "alternate",
        "href": "https://MY_DOMAIN.COM/pt/",
        "hreflang": "pt-br"
      }
    ],
    [
      "link",
      {
        "rel": "alternate",
        "href": "https://MY_DOMAIN.COM/es/",
        "hreflang": "es"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://connect.facebook.net/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://platform.twitter.com/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://widget.sndcdn.com/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://api-widget.soundcloud.com/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://www.youtube.com/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://scrimba.com/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://fonts.gstatic.com/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://c.disquscdn.com/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://disqus.com/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://www.google-analytics.com/"
      }
    ],
    [
      "link",
      {
        "rel": "preconnect",
        "href": "https://stats.g.doubleclick.net"
      }
    ],
    [
      "link",
      {
        "rel": "preload",
        "href": "https://www.google-analytics.com/analytics.js",
        "as": "script"
      }
    ]
  ],
  "pages": [
    {
      "title": "Rude Boy Enterprises",
      "frontmatter": {
        "view": "home",
        "title": "Rude Boy Enterprises",
        "description": "Projects and Articles by Samuel C Tyler",
        "lang": "en",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/rbe-banner.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/rbe-banner.png"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3d75f994",
      "path": "/"
    },
    {
      "title": "About us",
      "frontmatter": {
        "view": "page",
        "title": "About us",
        "description": "Find out more about the articles and video platform on web development and lifestyle, ktquez Play by Alan Ktquez.",
        "excerpt": "Making web development even more interesting",
        "ctaContact": true,
        "lang": "en",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-25ed5e18",
      "path": "/about/"
    },
    {
      "title": "All authors of Ktquez Play",
      "frontmatter": {
        "view": "authors",
        "title": "All authors of Ktquez Play",
        "description": "Find out who produces content on the articles and video platform on web development and Ktquez Play lifestyle",
        "lang": "en",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/authors/",
      "relativePath": "authors/README.md",
      "key": "v-06532fa2",
      "path": "/authors/"
    },
    {
      "title": "Articles by \"Skaman Sam\" Tyler",
      "frontmatter": {
        "view": "author",
        "lang": "en",
        "title": "Articles by \"Skaman Sam\" Tyler",
        "description": "Samuel Tyler is a 10 year full-stack software developer, specializing in Python, Ruby on Rails, Kubernetes, and Javascript.",
        "name": "\"Skaman Sam\" Tyler",
        "nickname": "skamansam",
        "role": "Web developer",
        "avatar": "/authors/skamansam.png",
        "created_at": "2020-04-08T00:00:00.000Z",
        "social": [
          {
            "name": "twitter",
            "url": "https://twitter.com/skamansam"
          },
          {
            "name": "github",
            "url": "https://github.com/skamansam"
          },
          {
            "name": "site",
            "url": "https://rubeboy.dev"
          }
        ],
        "meta": [
          {
            "property": "og:image",
            "content": "https://rudeboy.dev/authors/skamansam.png"
          },
          {
            "name": "twitter:image",
            "content": "https://rudeboy.dev/authors/skamansam.png"
          }
        ]
      },
      "regularPath": "/authors/skamansam.html",
      "relativePath": "authors/skamansam.md",
      "key": "v-625996b2",
      "path": "/authors/skamansam.html"
    },
    {
      "title": "Search for posts by keywords",
      "frontmatter": {
        "view": "categories",
        "title": "Search for posts by keywords",
        "excerpt": "Categories and tags for you to find what you want faster",
        "description": "Here you find all categories of the platform and a practice way to find articles through the tags of Ktquez Play",
        "lang": "en",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/",
      "relativePath": "categories/README.md",
      "key": "v-595cb904",
      "path": "/categories/"
    },
    {
      "title": "Javascript",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 2,
        "title": "Javascript",
        "description": "Javascript is the languages of this decade, but there is still a lot to learn. What comes out of novelty, we talk here.",
        "excerpt": "Javascript is the languages of this decade.",
        "slug": "javascript",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/javascript.html",
      "relativePath": "categories/javascript.md",
      "key": "v-e001bbf2",
      "path": "/categories/javascript.html"
    },
    {
      "title": "Linux",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 6,
        "title": "Linux",
        "description": "Information and Tutorials about Linux",
        "excerpt": "Information about Linux",
        "slug": "linux",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/linux.html",
      "relativePath": "categories/linux.md",
      "key": "v-dc94ec1e",
      "path": "/categories/linux.html"
    },
    {
      "title": "Open Source",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 1,
        "title": "Open Source",
        "description": "News Concerning Open Source Software",
        "excerpt": "Open Source News!",
        "slug": "open-source",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/open-source.html",
      "relativePath": "categories/open-source.md",
      "key": "v-83a40ec6",
      "path": "/categories/open-source.html"
    },
    {
      "title": "Perl",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 7,
        "title": "Perl",
        "description": "Projects and information on Perl.",
        "excerpt": "Perl projects",
        "slug": "perl",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/perl.html",
      "relativePath": "categories/perl.md",
      "key": "v-324b4a72",
      "path": "/categories/perl.html"
    },
    {
      "title": "Personal",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 12,
        "top": true,
        "title": "Personal",
        "description": "Random stuff about Samuel Tyler and his life, if you are interested.",
        "excerpt": "Rando",
        "slug": "personal",
        "meta": [
          {
            "property": "og:image",
            "content": "images/rbe-banner.png"
          },
          {
            "name": "twitter:image",
            "content": "images/rbe-banner.png"
          }
        ]
      },
      "regularPath": "/categories/personal.html",
      "relativePath": "categories/personal.md",
      "key": "v-4f2f5032",
      "path": "/categories/personal.html"
    },
    {
      "title": "Perl",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 1,
        "title": "Perl",
        "description": "Highlighted Projects On Which I Have Worked",
        "excerpt": "Portfolio of Things I Have Done",
        "slug": "portfolio",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/portfolio.html",
      "relativePath": "categories/portfolio.md",
      "key": "v-73288cc9",
      "path": "/categories/portfolio.html"
    },
    {
      "title": "General Programming",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 2,
        "title": "General Programming",
        "description": "Tips and Tricks for programming, in general",
        "excerpt": "General Tips and Tricks for Programming",
        "slug": "programming",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/programming.html",
      "relativePath": "categories/programming.md",
      "key": "v-688a7667",
      "path": "/categories/programming.html"
    },
    {
      "title": "Ruby",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 6,
        "top": true,
        "title": "Ruby",
        "description": "Ruby information and projects",
        "excerpt": "Ruby projects",
        "slug": "ruby",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/ruby.html",
      "relativePath": "categories/ruby.md",
      "key": "v-64d324a7",
      "path": "/categories/ruby.html"
    },
    {
      "title": "Vue.js",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 3,
        "top": true,
        "title": "Vue.js",
        "description": "Vue.js is the most successful javascript framework in recent years and certainly has its special space here in Ktquez play.",
        "excerpt": "Vue.js is the most successful javascript framework in recent years",
        "slug": "vuejs",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/vuejs.html",
      "relativePath": "categories/vuejs.md",
      "key": "v-19db9e7b",
      "path": "/categories/vuejs.html"
    },
    {
      "title": "Web Development",
      "frontmatter": {
        "view": "category",
        "lang": "en",
        "order": 4,
        "title": "Web Development",
        "description": "General Web Development - HTML/CSS, tips and tricks",
        "excerpt": "General HTML/CSS tips and tricks",
        "slug": "web-development",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/categories/web-development.html",
      "relativePath": "categories/web-development.md",
      "key": "v-71fdacd6",
      "path": "/categories/web-development.html"
    },
    {
      "title": "Happy to be here at Ktquez play and looking forward to a chat",
      "frontmatter": {
        "view": "page",
        "title": "Happy to be here at Ktquez play and looking forward to a chat",
        "description": "Contact Ktquez play about events, partnerships, blog questions and courses, contact with our team, among others.",
        "excerpt": "Contact us about events, partnerships, blog questions and courses, contact with our team, among others.",
        "lang": "en",
        "meta": [
          {
            "property": "og:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          },
          {
            "name": "twitter:image",
            "content": "https://ktquez.com/share/ktquez-play-image-share.png"
          }
        ]
      },
      "regularPath": "/contact/",
      "relativePath": "contact/README.md",
      "key": "v-4968f81c",
      "path": "/contact/"
    },
    {
      "title": "Welcome To My Blog!",
      "frontmatter": {
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Welcome To My Blog!",
        "description": "A little bit about myself and my blog.",
        "excerpt": "Hello, all! This is the blog for \"Skaman Sam\" Tyler, founder of Rude Boy Enterprises.",
        "cover": true,
        "coverAlt": "RBE Logo",
        "demo": null,
        "audio": null,
        "categories": [
          "personal"
        ],
        "tags": [
          "about"
        ],
        "created_at": "2008-03-05 19:44",
        "updated_at": "2008-03-05 19:44",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/rbe-banner.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/rbe-banner.png"
          }
        ]
      },
      "regularPath": "/posts/2008-03-05-welcome-to-my-blog.html",
      "relativePath": "posts/2008-03-05-welcome-to-my-blog.md",
      "key": "v-7caa0a27",
      "path": "/posts/2008-03-05-welcome-to-my-blog.html"
    },
    {
      "title": "Accepted Into Google Summer of Code!",
      "frontmatter": {
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Accepted Into Google Summer of Code!",
        "description": "GUI for CPAN",
        "excerpt": "I got accepted into Google's Summer of Code! My project is a GUI for CPAN.",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "personal"
        ],
        "tags": [
          "gSoC"
        ],
        "created_at": "2008-04-23 15:24",
        "updated_at": "2008-04-23 15:24",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2008-04-23-accepted-into-google-summer-of-code.html",
      "relativePath": "posts/2008-04-23-accepted-into-google-summer-of-code.md",
      "key": "v-0ef6a32a",
      "path": "/posts/2008-04-23-accepted-into-google-summer-of-code.html"
    },
    {
      "title": "wxCPAN Skeleton Code",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "wxCPAN Skeleton Code",
        "description": "wxCPAN is underway!",
        "excerpt": "I have started doing heavy-duty research into wxPerl",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "perl"
        ],
        "tags": [
          "gSoC"
        ],
        "created_at": "2008-05-09 14:40",
        "updated_at": "2008-05-09 14:40",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2008-05-09-wxcpan-skeleton-code.html",
      "relativePath": "posts/2008-05-09-wxcpan-skeleton-code.md",
      "key": "v-ab6f9872",
      "path": "/posts/2008-05-09-wxcpan-skeleton-code.html"
    },
    {
      "title": "wxCPAN Going Well",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "wxCPAN Going Well",
        "description": "wxCPAN Going Well",
        "excerpt": "I have successfully managed to implement a CPANPLUS::Shell.",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "perl"
        ],
        "tags": [
          "gSoC"
        ],
        "created_at": "2008-05-13 14:56",
        "updated_at": "2008-05-13 14:56",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2008-05-13-wxcpan-going-well.html",
      "relativePath": "posts/2008-05-13-wxcpan-going-well.md",
      "key": "v-4d6dbde9",
      "path": "/posts/2008-05-13-wxcpan-going-well.html"
    },
    {
      "title": "gSoC_Day[0]='Hit The Ground Running';",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "gSoC_Day[0]='Hit The Ground Running';",
        "description": "It is now day 0 for gSoC",
        "excerpt": "I have hit the ground running and am off to a good start",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "perl"
        ],
        "tags": [
          "gSoC"
        ],
        "created_at": "2008-05-24 13:41",
        "updated_at": "2008-05-24 13:41",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2008-05-24-gsoc-day-0-equals-hit-the-ground-running.html",
      "relativePath": "posts/2008-05-24-gsoc-day-0-equals-hit-the-ground-running.md",
      "key": "v-4418ef07",
      "path": "/posts/2008-05-24-gsoc-day-0-equals-hit-the-ground-running.html"
    },
    {
      "title": "My Baby",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "My Baby",
        "description": "pictures of my baby",
        "excerpt": "auto uploaded pics of my baby",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "personal"
        ],
        "tags": [
          "Photographs"
        ],
        "created_at": "2008-08-05 17:18",
        "updated_at": "2020-06-17 01:34",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2008-08-05-my-baby.html",
      "relativePath": "posts/2008-08-05-my-baby.md",
      "key": "v-d77d7ebe",
      "path": "/posts/2008-08-05-my-baby.html"
    },
    {
      "title": "My Baby 2",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "My Baby 2",
        "description": "more pictures of my baby",
        "excerpt": "auto uploaded pics of my baby",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "personal"
        ],
        "tags": [
          "Photographs"
        ],
        "created_at": "2008-08-05 17:18",
        "updated_at": "2020-06-17 01:34",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2008-08-05-my-baby2.html",
      "relativePath": "posts/2008-08-05-my-baby2.md",
      "key": "v-09948067",
      "path": "/posts/2008-08-05-my-baby2.html"
    },
    {
      "title": "my bartender, mark",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "my bartender, mark",
        "description": "pictures of my bartender, mark",
        "excerpt": "auto uploaded pics of my bartender, mark",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "personal"
        ],
        "tags": [
          "Photographs"
        ],
        "created_at": "2008-08-05 16:34",
        "updated_at": "2020-06-17 01:34",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2008-08-05-my-bartender-mark.html",
      "relativePath": "posts/2008-08-05-my-bartender-mark.md",
      "key": "v-1a4255b2",
      "path": "/posts/2008-08-05-my-bartender-mark.html"
    },
    {
      "title": "al at werk again",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "al at werk again",
        "description": "pictures of al at werk again",
        "excerpt": "auto uploaded pics of al at werk again",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "personal"
        ],
        "tags": [
          "Photographs"
        ],
        "created_at": "2008-08-07 14:36",
        "updated_at": "2020-06-17 01:34",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2008-08-07-al-at-werk-again.html",
      "relativePath": "posts/2008-08-07-al-at-werk-again.md",
      "key": "v-6d1ef847",
      "path": "/posts/2008-08-07-al-at-werk-again.html"
    },
    {
      "title": "al at werk",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "al at werk",
        "description": "pictures of al at werk",
        "excerpt": "auto uploaded pics of al at werk",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "personal"
        ],
        "tags": [
          "Photographs"
        ],
        "created_at": "2008-08-07 14:38",
        "updated_at": "2020-06-17 01:34",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2008-08-07-al-at-werk.html",
      "relativePath": "posts/2008-08-07-al-at-werk.md",
      "key": "v-01fdfde7",
      "path": "/posts/2008-08-07-al-at-werk.html"
    },
    {
      "title": "WebFX at UNCG",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "WebFX at UNCG",
        "description": "Framework of js effects",
        "excerpt": "Last semester, I started a project to ease my work quite a bit.",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "portfolio",
          "javascript"
        ],
        "tags": [
          "UNCG",
          "Web Design"
        ],
        "created_at": "2009-01-08 10:49",
        "updated_at": "2009-01-08 10:49",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-01-08-webfx-at-uncg.html",
      "relativePath": "posts/2009-01-08-webfx-at-uncg.md",
      "key": "v-3cceb24e",
      "path": "/posts/2009-01-08-webfx-at-uncg.html",
      "headers": [
        {
          "level": 2,
          "title": "Effects",
          "slug": "effects"
        },
        {
          "level": 3,
          "title": "Always-Visible (class=\"webFX_alwaysVisible\")",
          "slug": "always-visible-class-webfx-alwaysvisible"
        },
        {
          "level": 3,
          "title": "Image Rotation (class=\"webFX_rotate\")",
          "slug": "image-rotation-class-webfx-rotate"
        },
        {
          "level": 3,
          "title": "Slideshow (class=\"webFX_slideshow\")",
          "slug": "slideshow-class-webfx-slideshow"
        },
        {
          "level": 3,
          "title": "Gallery (class=\"webFX_gallery\")",
          "slug": "gallery-class-webfx-gallery"
        },
        {
          "level": 2,
          "title": "User Interface",
          "slug": "user-interface"
        },
        {
          "level": 3,
          "title": "Accordion (class=\"webFX_accordion\")",
          "slug": "accordion-class-webfx-accordion"
        },
        {
          "level": 3,
          "title": "Tabbed Navigation (class=\"webFX_tabs\")",
          "slug": "tabbed-navigation-class-webfx-tabs"
        },
        {
          "level": 3,
          "title": "DatePicker (class=\"webFX_datePicker\")",
          "slug": "datepicker-class-webfx-datepicker"
        },
        {
          "level": 3,
          "title": "Dialog (class=\"webFX_dialog\")",
          "slug": "dialog-class-webfx-dialog"
        },
        {
          "level": 3,
          "title": "Slider (class=\"webFX_dialog\")",
          "slug": "slider-class-webfx-dialog"
        },
        {
          "level": 2,
          "title": "Styles",
          "slug": "styles"
        },
        {
          "level": 3,
          "title": "News (class=\"webFX_news\")",
          "slug": "news-class-webfx-news"
        }
      ]
    },
    {
      "title": "Installing Gentoo 2008 in (qemu) Sun's VirtualBox on Fedora 10",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Installing Gentoo 2008 in (qemu) Sun's VirtualBox on Fedora 10",
        "description": "Information on virtual OSs and benchmarks",
        "excerpt": "I am currently taking a class on Operating System design and need to do some kernel hacking for the class.",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "linux"
        ],
        "tags": [
          "Fedora",
          "VirtualBox",
          "Gentoo"
        ],
        "created_at": "2009-02-02 08:31",
        "updated_at": "2009-02-02 08:31",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-02-02-installing-gentoo-2008-in-qemu-suns-virtualbox-on-fedora-10.html",
      "relativePath": "posts/2009-02-02-installing-gentoo-2008-in-qemu-suns-virtualbox-on-fedora-10.md",
      "key": "v-91e81f56",
      "path": "/posts/2009-02-02-installing-gentoo-2008-in-qemu-suns-virtualbox-on-fedora-10.html",
      "headers": [
        {
          "level": 2,
          "title": "nbench result for host OS (Fedora 10 x86_64 on Intel Core 2 Duo w/ 4Gb RAM):",
          "slug": "nbench-result-for-host-os-fedora-10-x86-64-on-intel-core-2-duo-w-4gb-ram"
        },
        {
          "level": 2,
          "title": "nbench result for Gentoo 2008 x86_64 on Sun VirtualBox (w/ 768 Mb RAM):",
          "slug": "nbench-result-for-gentoo-2008-x86-64-on-sun-virtualbox-w-768-mb-ram"
        }
      ]
    },
    {
      "title": "Drop-Down Menu with CSS",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Drop-Down Menu with CSS",
        "description": "Drop-down menu with no JS",
        "excerpt": "The CSS Drop-down Menu is fairly simple.",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development"
        ],
        "tags": [
          "CSS"
        ],
        "created_at": "2009-02-09 08:48",
        "updated_at": "2009-02-09 08:48",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-02-09-drop-down-menu-with-css.html",
      "relativePath": "posts/2009-02-09-drop-down-menu-with-css.md",
      "key": "v-42a1e782",
      "path": "/posts/2009-02-09-drop-down-menu-with-css.html",
      "headers": [
        {
          "level": 2,
          "title": "Problem 1: Internet Explorer",
          "slug": "problem-1-internet-explorer"
        },
        {
          "level": 2,
          "title": "Ugly!",
          "slug": "ugly"
        }
      ]
    },
    {
      "title": "Installing Aptana in Fedora Eclipse",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Installing Aptana in Fedora Eclipse",
        "description": "Installing Aptana in Fedora Eclipse",
        "excerpt": "Aptana is a wonderful tool for web design.",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development",
          "linux"
        ],
        "tags": [
          "CSS",
          "Fedora",
          "IDE",
          "Editor"
        ],
        "created_at": "2009-02-14 12:09",
        "updated_at": "2009-02-14 12:09",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-02-14-installing-aptana-in-fedora-eclipse.html",
      "relativePath": "posts/2009-02-14-installing-aptana-in-fedora-eclipse.md",
      "key": "v-aba30b82",
      "path": "/posts/2009-02-14-installing-aptana-in-fedora-eclipse.html",
      "headers": [
        {
          "level": 3,
          "title": "Keep Installed:",
          "slug": "keep-installed"
        },
        {
          "level": 3,
          "title": "Install Using Aptana:",
          "slug": "install-using-aptana"
        },
        {
          "level": 3,
          "title": "Install Using The Update Manager:",
          "slug": "install-using-the-update-manager"
        }
      ]
    },
    {
      "title": "Building Chromium on Fedora 10 x86_64",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Building Chromium on Fedora 10 x86_64",
        "description": "Installing Chromium for Fedora 10 x86_64 bit",
        "excerpt": "Chromium for Fedora 10 x86_64 bit",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development",
          "linux"
        ],
        "tags": [
          "CSS",
          "Fedora",
          "IDE",
          "Editor"
        ],
        "created_at": "2009-03-11 7:50",
        "updated_at": "2009-03-11 7:50",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-03-11-building-chromium-on-fedora-10-x86-64.html",
      "relativePath": "posts/2009-03-11-building-chromium-on-fedora-10-x86-64.md",
      "key": "v-bf119fe2",
      "path": "/posts/2009-03-11-building-chromium-on-fedora-10-x86-64.html"
    },
    {
      "title": "Windows vs. Linux on MSI GX700",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Windows vs. Linux on MSI GX700",
        "description": "Comparing Windows and Linux on MSI GX700",
        "excerpt": "I try to buy MSI products whenever possible",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "linux"
        ],
        "tags": [
          "Fedora",
          "Hardware"
        ],
        "created_at": "2009-03-21 9:32",
        "updated_at": "2009-03-21 9:32",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-03-21-windows-vs-linux-on-msi-gx700.html",
      "relativePath": "posts/2009-03-21-windows-vs-linux-on-msi-gx700.md",
      "key": "v-2915d3f5",
      "path": "/posts/2009-03-21-windows-vs-linux-on-msi-gx700.html",
      "headers": [
        {
          "level": 2,
          "title": "Windows Vista 64bit",
          "slug": "windows-vista-64bit"
        },
        {
          "level": 3,
          "title": "Problems",
          "slug": "problems"
        },
        {
          "level": 2,
          "title": "Fedora 10 x86_64",
          "slug": "fedora-10-x86-64"
        },
        {
          "level": 3,
          "title": "Problems",
          "slug": "problems-2"
        }
      ]
    },
    {
      "title": "jQuery Style Sheet (CSS) Switcher",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "jQuery Style Sheet (CSS) Switcher",
        "description": "Building a CSS Switcher using jQuery",
        "excerpt": "I try to buy MSI products whenever possible",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development",
          "javascript"
        ],
        "tags": [
          "jQuery",
          "CSS"
        ],
        "created_at": "2009-04-01 18:16",
        "updated_at": "2009-04-01 18:16",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-04-01-jquery-style-sheet-css-switcher.html",
      "relativePath": "posts/2009-04-01-jquery-style-sheet-css-switcher.md",
      "key": "v-0702ed76",
      "path": "/posts/2009-04-01-jquery-style-sheet-css-switcher.html"
    },
    {
      "title": "Building Enlightenment e17 on Fedora 10 x86_64",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Building Enlightenment e17 on Fedora 10 x86_64",
        "description": "How to Build Enlightenment Desktop on Fedora 10",
        "excerpt": "i have begun to build and install Enlightenment e17 on my Fedora 10 x86_64 laptop",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "linux"
        ],
        "tags": [
          "Fedora"
        ],
        "created_at": "2009-04-02 21:34",
        "updated_at": "2009-04-02 21:34",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-04-02-building-enlightenment-e17-on-fedora-10-x86-64.html",
      "relativePath": "posts/2009-04-02-building-enlightenment-e17-on-fedora-10-x86-64.md",
      "key": "v-4cee78b2",
      "path": "/posts/2009-04-02-building-enlightenment-e17-on-fedora-10-x86-64.html",
      "headers": [
        {
          "level": 2,
          "title": "Step 1: Preparations",
          "slug": "step-1-preparations"
        },
        {
          "level": 2,
          "title": "Step 2: The long drive home",
          "slug": "step-2-the-long-drive-home"
        },
        {
          "level": 3,
          "title": "Ememoa [ ememoa-read-only/ ]  --enable-pthread --enable-use64</dt>",
          "slug": "ememoa-ememoa-read-only-enable-pthread-enable-use64"
        },
        {
          "level": 3,
          "title": "Imlib2 [ imlib2/ ]",
          "slug": "imlib2-imlib2"
        },
        {
          "level": 3,
          "title": "eina [ eina/ ] --enable-ememoa",
          "slug": "eina-eina-enable-ememoa"
        },
        {
          "level": 3,
          "title": "Eet [ eet/ ]",
          "slug": "eet-eet"
        },
        {
          "level": 3,
          "title": "Edb [ OLD/edb/ ]",
          "slug": "edb-old-edb"
        },
        {
          "level": 3,
          "title": "Imlib2 Extras [ imlib2_loaders/ ]",
          "slug": "imlib2-extras-imlib2-loaders"
        },
        {
          "level": 3,
          "title": "Imlib2 Extras [ imlib2_tools/ ]",
          "slug": "imlib2-extras-imlib2-tools"
        },
        {
          "level": 3,
          "title": "Evas [ evas/ ] --enable-gl-x11 --enable-gl-glew --enable-software-xcb --enable-buffer --enable-xrender-x11 --enable-software-sdl --enable-directfb --enable-fb",
          "slug": "evas-evas-enable-gl-x11-enable-gl-glew-enable-software-xcb-enable-buffer-enable-xrender-x11-enable-software-sdl-enable-directfb-enable-fb"
        },
        {
          "level": 3,
          "title": "Ecore [ ecore/ ]",
          "slug": "ecore-ecore"
        },
        {
          "level": 3,
          "title": "Efreet [ efreet/ ]",
          "slug": "efreet-efreet"
        },
        {
          "level": 3,
          "title": "Embryo [ embryo/ ] --enable-doc",
          "slug": "embryo-embryo-enable-doc"
        },
        {
          "level": 3,
          "title": "Edje [edje/] --enable-doc --enable-edje-program-cache",
          "slug": "edje-edje-enable-doc-enable-edje-program-cache"
        },
        {
          "level": 3,
          "title": "EDBus [ edbus/ ]",
          "slug": "e-dbus-e-dbus"
        },
        {
          "level": 3,
          "title": "ETK [ etk/ ]",
          "slug": "etk-etk"
        },
        {
          "level": 3,
          "title": "EXML [ exml/ ]",
          "slug": "exml-exml"
        },
        {
          "level": 3,
          "title": "Epsilon [ epsilon/ ] --enable-thumbnailer-xine",
          "slug": "epsilon-epsilon-enable-thumbnailer-xine"
        },
        {
          "level": 3,
          "title": "Emotion [ epsilon/ ]",
          "slug": "emotion-epsilon"
        },
        {
          "level": 3,
          "title": "Enity [ enity/ ]",
          "slug": "enity-enity"
        },
        {
          "level": 3,
          "title": "Etk Extras [ etk_extra/ ]",
          "slug": "etk-extras-etk-extra"
        },
        {
          "level": 3,
          "title": "Evolve [ evolve/ ]",
          "slug": "evolve-evolve"
        },
        {
          "level": 3,
          "title": "Enlightenment Widget Library [ ewl/ ]",
          "slug": "enlightenment-widget-library-ewl"
        },
        {
          "level": 3,
          "title": "Expedite [ expedite/ ]",
          "slug": "expedite-expedite"
        },
        {
          "level": 3,
          "title": "Enhance [ enhance/ ]",
          "slug": "enhance-enhance"
        },
        {
          "level": 3,
          "title": "Exchange [ PROTO/exchange/ ]",
          "slug": "exchange-proto-exchange"
        },
        {
          "level": 3,
          "title": "Esmart [ esmart/ ]",
          "slug": "esmart-esmart"
        },
        {
          "level": 3,
          "title": "Enlightenment [ e/ ]",
          "slug": "enlightenment-e"
        },
        {
          "level": 3,
          "title": "Entrance [ entrance/ ]",
          "slug": "entrance-entrance"
        },
        {
          "level": 2,
          "title": "Step 3: EApps",
          "slug": "step-3-eapps"
        },
        {
          "level": 3,
          "title": "Edje Editor [ edje_editor/ ]",
          "slug": "edje-editor-edje-editor"
        },
        {
          "level": 3,
          "title": "Edje Viewer [ edje_editor/ ]",
          "slug": "edje-viewer-edje-editor"
        },
        {
          "level": 3,
          "title": "Elicit [ elicit/ ]",
          "slug": "elicit-elicit"
        },
        {
          "level": 3,
          "title": "Elitaire [ elitaire/ ]",
          "slug": "elitaire-elitaire"
        }
      ]
    },
    {
      "title": "Google Summer of Code 2009 Project Ideas",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Google Summer of Code 2009 Project Ideas",
        "description": "List of projects for GSoC 2009",
        "excerpt": "Google has announced a another Summer of Code for 2009",
        "cover": false,
        "coverImage": "/images/GSoC-logo-horizontal-800.png",
        "coverAlt": "RBE Logo",
        "categories": [
          "open-source"
        ],
        "tags": [
          "Google Summer of Code"
        ],
        "created_at": "2009-04-02T21:31:00.000Z",
        "updated_at": "2009-04-02T21:31:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-04-02-google-summer-of-code-2009-project-ideas.html",
      "relativePath": "posts/2009-04-02-google-summer-of-code-2009-project-ideas.md",
      "key": "v-15e8dc72",
      "path": "/posts/2009-04-02-google-summer-of-code-2009-project-ideas.html"
    },
    {
      "title": "TeTex for Puppy Linux",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "TeTex for Puppy Linux",
        "description": "Creating a TeTex .pup for Puppy Linux 4.20",
        "excerpt": "I really wanted tetex and a good editor, but don't really like installing pups/pets",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "linux"
        ],
        "tags": [
          "Puppy Linux"
        ],
        "created_at": "2009-05-10T17:02:00.000Z",
        "updated_at": "2009-05-10T17:02:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-05-10-tetex-for-puppy-linux.html",
      "relativePath": "posts/2009-05-10-tetex-for-puppy-linux.md",
      "key": "v-4b934e93",
      "path": "/posts/2009-05-10-tetex-for-puppy-linux.html"
    },
    {
      "title": "Fun With Numbers! (revised)",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Fun With Numbers! (revised)",
        "description": "How to Find polynomial coefficients using Pascal's Triangle",
        "excerpt": "I have always had a certain love for math and the neat things you can do with it.",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "programming"
        ],
        "tags": [
          "Math",
          "Pascal's Triangle",
          "Polynomials"
        ],
        "created_at": "2009-05-29T08:48:00.000Z",
        "updated_at": "2016-09-14T07:56:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-05-29-fun-with-numbers.html",
      "relativePath": "posts/2009-05-29-fun-with-numbers.md",
      "key": "v-68a02f67",
      "path": "/posts/2009-05-29-fun-with-numbers.html",
      "headers": [
        {
          "level": 2,
          "title": "Pascal's Triangle",
          "slug": "pascal-s-triangle"
        },
        {
          "level": 2,
          "title": "Binomial Expansion",
          "slug": "binomial-expansion"
        },
        {
          "level": 3,
          "title": "Features",
          "slug": "features"
        },
        {
          "level": 3,
          "title": "Does your binomial already have coefficients?",
          "slug": "does-your-binomial-already-have-coefficients"
        }
      ]
    },
    {
      "title": "How To Repair Images with ImageMagick",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "How To Repair Images with ImageMagick",
        "description": "Using ImageMagick to repair corrupted images",
        "excerpt": "the images [...] were taken with my phone's camera and all had errors",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development"
        ],
        "tags": [
          "Coppermine",
          "Image Repair"
        ],
        "created_at": "2009-06-15T11:23:00.000Z",
        "updated_at": "2009-06-15T11:23:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-06-15-how-to-repair-images-with-imagemagick.html",
      "relativePath": "posts/2009-06-15-how-to-repair-images-with-imagemagick.md",
      "key": "v-6913dd53",
      "path": "/posts/2009-06-15-how-to-repair-images-with-imagemagick.html"
    },
    {
      "title": "New Theme Under Construction...",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "New Theme Under Construction...",
        "description": "New Theme Under Construction...",
        "excerpt": "I am creating a new theme for WordPress called Bubbly Blue",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development"
        ],
        "tags": [
          "Theme"
        ],
        "created_at": "2009-07-31T09:25:00.000Z",
        "updated_at": "2009-08-09T09:25:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2009-07-31-new-theme-under-construction-dot-dot-dot.html",
      "relativePath": "posts/2009-07-31-new-theme-under-construction-dot-dot-dot.md",
      "key": "v-01095047",
      "path": "/posts/2009-07-31-new-theme-under-construction-dot-dot-dot.html",
      "headers": [
        {
          "level": 3,
          "title": "Updated August 9:",
          "slug": "updated-august-9"
        }
      ]
    },
    {
      "title": "Teaching Computer Science in a Web Browser?",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Teaching Computer Science in a Web Browser?",
        "description": "Ideas on how to teach CSC courses using only a web browser",
        "excerpt": null,
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "programming"
        ],
        "tags": [
          "Education",
          "Online Education"
        ],
        "created_at": "2010-06-02T21:48:00.000Z",
        "updated_at": "2010-06-02T21:48:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2010-06-02-teaching-computer-science-in-a-web-browser.html",
      "relativePath": "posts/2010-06-02-teaching-computer-science-in-a-web-browser.md",
      "key": "v-65bf4247",
      "path": "/posts/2010-06-02-teaching-computer-science-in-a-web-browser.html",
      "headers": [
        {
          "level": 2,
          "title": "General Programming Courses",
          "slug": "general-programming-courses"
        },
        {
          "level": 2,
          "title": "Graphics",
          "slug": "graphics"
        },
        {
          "level": 2,
          "title": "Algorithms",
          "slug": "algorithms"
        },
        {
          "level": 3,
          "title": "230 Elementary Data Structures and Algorithms",
          "slug": "_230-elementary-data-structures-and-algorithms"
        },
        {
          "level": 2,
          "title": "Networking",
          "slug": "networking"
        },
        {
          "level": 2,
          "title": "Math-Based Courses",
          "slug": "math-based-courses"
        },
        {
          "level": 3,
          "title": "250 Foundations of Computer Science I",
          "slug": "_250-foundations-of-computer-science-i"
        },
        {
          "level": 2,
          "title": "Hardware",
          "slug": "hardware"
        },
        {
          "level": 3,
          "title": "261 Computer Organization and Assembly Language",
          "slug": "_261-computer-organization-and-assembly-language"
        },
        {
          "level": 2,
          "title": "Outside the Browser",
          "slug": "outside-the-browser"
        },
        {
          "level": 3,
          "title": "330 Advanced Data Structures",
          "slug": "_330-advanced-data-structures"
        },
        {
          "level": 3,
          "title": "339 Concepts of Programming Languages",
          "slug": "_339-concepts-of-programming-languages"
        },
        {
          "level": 3,
          "title": "340 Software Engineering",
          "slug": "_340-software-engineering"
        },
        {
          "level": 3,
          "title": "350 Foundations of Computer Science II",
          "slug": "_350-foundations-of-computer-science-ii"
        },
        {
          "level": 3,
          "title": "463 Basic Systems Administration Laboratory",
          "slug": "_463-basic-systems-administration-laboratory"
        },
        {
          "level": 3,
          "title": "464 Intermediate Systems Administration Laboratory",
          "slug": "_464-intermediate-systems-administration-laboratory"
        },
        {
          "level": 3,
          "title": "465 Advanced Systems Administration Laboratory",
          "slug": "_465-advanced-systems-administration-laboratory"
        },
        {
          "level": 3,
          "title": "471 Principles of Database Systems",
          "slug": "_471-principles-of-database-systems"
        },
        {
          "level": 3,
          "title": "490 Senior Project",
          "slug": "_490-senior-project"
        },
        {
          "level": 3,
          "title": "493 Honors Work in Computer Science",
          "slug": "_493-honors-work-in-computer-science"
        },
        {
          "level": 3,
          "title": "495 Selected Topics in Computer Science",
          "slug": "_495-selected-topics-in-computer-science"
        },
        {
          "level": 3,
          "title": "521 Computer Graphics",
          "slug": "_521-computer-graphics"
        },
        {
          "level": 3,
          "title": "522 Digital Image Processing",
          "slug": "_522-digital-image-processing"
        },
        {
          "level": 3,
          "title": "523 Numerical Analysis and Computing",
          "slug": "_523-numerical-analysis-and-computing"
        },
        {
          "level": 3,
          "title": "524 Numerical Analysis and Computing",
          "slug": "_524-numerical-analysis-and-computing"
        },
        {
          "level": 3,
          "title": "526 Bioinformatics",
          "slug": "_526-bioinformatics"
        },
        {
          "level": 3,
          "title": "529 Artificial Intelligence",
          "slug": "_529-artificial-intelligence"
        },
        {
          "level": 3,
          "title": "539 Introduction to Compiler Design",
          "slug": "_539-introduction-to-compiler-design"
        },
        {
          "level": 3,
          "title": "540 Human-Computer Interface Development",
          "slug": "_540-human-computer-interface-development"
        },
        {
          "level": 3,
          "title": "550 Combinatorics on Words",
          "slug": "_550-combinatorics-on-words"
        },
        {
          "level": 3,
          "title": "553 Theory of Computation",
          "slug": "_553-theory-of-computation"
        },
        {
          "level": 3,
          "title": "555 Algorithm Analysis and Design",
          "slug": "_555-algorithm-analysis-and-design"
        },
        {
          "level": 3,
          "title": "561 Principles of Computer Architecture",
          "slug": "_561-principles-of-computer-architecture"
        },
        {
          "level": 3,
          "title": "562 Principles of Operating Systems",
          "slug": "_562-principles-of-operating-systems"
        },
        {
          "level": 3,
          "title": "567 Principles of Computer Networks",
          "slug": "_567-principles-of-computer-networks"
        },
        {
          "level": 3,
          "title": "568 Principles of Wireless Networks",
          "slug": "_568-principles-of-wireless-networks"
        },
        {
          "level": 3,
          "title": "580 Cryptography and Security in Computing",
          "slug": "_580-cryptography-and-security-in-computing"
        },
        {
          "level": 3,
          "title": "583 Firewall Architecture and Computer Security",
          "slug": "_583-firewall-architecture-and-computer-security"
        }
      ]
    },
    {
      "title": "Teaching Computer Science in a Web Browser?",
      "frontmatter": {
        "published": false,
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Teaching Computer Science in a Web Browser?",
        "description": "Ideas on how to teach CSC courses using only a web browser",
        "excerpt": null,
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "programming"
        ],
        "tags": [
          "Education",
          "Online Education",
          "Computer Science"
        ],
        "created_at": "2010-06-15T08:28:37.000Z",
        "updated_at": "2010-06-15T08:28:37.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2010-06-15-teaching-computer-science-in-a-web-browser.html",
      "relativePath": "posts/2010-06-15-teaching-computer-science-in-a-web-browser.md",
      "key": "v-33a34607",
      "path": "/posts/2010-06-15-teaching-computer-science-in-a-web-browser.html",
      "headers": [
        {
          "level": 2,
          "title": "General Programming Courses",
          "slug": "general-programming-courses"
        },
        {
          "level": 2,
          "title": "Graphics",
          "slug": "graphics"
        },
        {
          "level": 2,
          "title": "Algorithms",
          "slug": "algorithms"
        },
        {
          "level": 3,
          "title": "230 Elementary Data Structures and Algorithms",
          "slug": "_230-elementary-data-structures-and-algorithms"
        },
        {
          "level": 2,
          "title": "Networking",
          "slug": "networking"
        },
        {
          "level": 2,
          "title": "Math-Based Courses",
          "slug": "math-based-courses"
        },
        {
          "level": 3,
          "title": "250 Foundations of Computer Science I",
          "slug": "_250-foundations-of-computer-science-i"
        },
        {
          "level": 2,
          "title": "Hardware",
          "slug": "hardware"
        },
        {
          "level": 3,
          "title": "261 Computer Organization and Assembly Language",
          "slug": "_261-computer-organization-and-assembly-language"
        },
        {
          "level": 2,
          "title": "Outside the Browser",
          "slug": "outside-the-browser"
        },
        {
          "level": 3,
          "title": "330 Advanced Data Structures",
          "slug": "_330-advanced-data-structures"
        },
        {
          "level": 3,
          "title": "339 Concepts of Programming Languages",
          "slug": "_339-concepts-of-programming-languages"
        },
        {
          "level": 3,
          "title": "340 Software Engineering",
          "slug": "_340-software-engineering"
        },
        {
          "level": 3,
          "title": "350 Foundations of Computer Science II",
          "slug": "_350-foundations-of-computer-science-ii"
        },
        {
          "level": 3,
          "title": "463 Basic Systems Administration Laboratory",
          "slug": "_463-basic-systems-administration-laboratory"
        },
        {
          "level": 3,
          "title": "464 Intermediate Systems Administration Laboratory",
          "slug": "_464-intermediate-systems-administration-laboratory"
        },
        {
          "level": 3,
          "title": "465 Advanced Systems Administration Laboratory",
          "slug": "_465-advanced-systems-administration-laboratory"
        },
        {
          "level": 3,
          "title": "471 Principles of Database Systems",
          "slug": "_471-principles-of-database-systems"
        },
        {
          "level": 3,
          "title": "490 Senior Project",
          "slug": "_490-senior-project"
        },
        {
          "level": 3,
          "title": "493 Honors Work in Computer Science",
          "slug": "_493-honors-work-in-computer-science"
        },
        {
          "level": 3,
          "title": "495 Selected Topics in Computer Science",
          "slug": "_495-selected-topics-in-computer-science"
        },
        {
          "level": 3,
          "title": "521 Computer Graphics",
          "slug": "_521-computer-graphics"
        },
        {
          "level": 3,
          "title": "522 Digital Image Processing",
          "slug": "_522-digital-image-processing"
        },
        {
          "level": 3,
          "title": "523 Numerical Analysis and Computing",
          "slug": "_523-numerical-analysis-and-computing"
        },
        {
          "level": 3,
          "title": "524 Numerical Analysis and Computing",
          "slug": "_524-numerical-analysis-and-computing"
        },
        {
          "level": 3,
          "title": "526 Bioinformatics",
          "slug": "_526-bioinformatics"
        },
        {
          "level": 3,
          "title": "529 Artificial Intelligence",
          "slug": "_529-artificial-intelligence"
        },
        {
          "level": 3,
          "title": "539 Introduction to Compiler Design",
          "slug": "_539-introduction-to-compiler-design"
        },
        {
          "level": 3,
          "title": "540 Human-Computer Interface Development",
          "slug": "_540-human-computer-interface-development"
        },
        {
          "level": 3,
          "title": "550 Combinatorics on Words",
          "slug": "_550-combinatorics-on-words"
        },
        {
          "level": 3,
          "title": "553 Theory of Computation",
          "slug": "_553-theory-of-computation"
        },
        {
          "level": 3,
          "title": "555 Algorithm Analysis and Design",
          "slug": "_555-algorithm-analysis-and-design"
        },
        {
          "level": 3,
          "title": "561 Principles of Computer Architecture",
          "slug": "_561-principles-of-computer-architecture"
        },
        {
          "level": 3,
          "title": "562 Principles of Operating Systems",
          "slug": "_562-principles-of-operating-systems"
        },
        {
          "level": 3,
          "title": "567 Principles of Computer Networks",
          "slug": "_567-principles-of-computer-networks"
        },
        {
          "level": 3,
          "title": "568 Principles of Wireless Networks",
          "slug": "_568-principles-of-wireless-networks"
        },
        {
          "level": 3,
          "title": "580 Cryptography and Security in Computing",
          "slug": "_580-cryptography-and-security-in-computing"
        },
        {
          "level": 3,
          "title": "583 Firewall Architecture and Computer Security",
          "slug": "_583-firewall-architecture-and-computer-security"
        }
      ]
    },
    {
      "title": "Tango Icons: Save All",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Tango Icons: Save All",
        "description": "A suggestion for a Save All icon for the Tango Project",
        "excerpt": "Ever notice how the Tango icons don't have a \"Save All\" icon?",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "programming"
        ],
        "tags": [
          "Education",
          "Online Education",
          "Computer Science"
        ],
        "created_at": "2010-07-28T14:35:00.000Z",
        "updated_at": "2010-07-28T14:35:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2010-07-28-tango-icons-save-all.html",
      "relativePath": "posts/2010-07-28-tango-icons-save-all.md",
      "key": "v-d9c5dd32",
      "path": "/posts/2010-07-28-tango-icons-save-all.html"
    },
    {
      "title": "jQuery ThemeSwitcherTool - Working Version!!!!!",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "jQuery ThemeSwitcherTool - Working Version!!!!!",
        "description": "A working version of my ThemeSwitcherTool",
        "excerpt": "I added a few extra options to cover the changes I made.",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development"
        ],
        "tags": [
          "jQuery"
        ],
        "created_at": "2011-03-06T21:20:00.000Z",
        "updated_at": "2011-03-06T21:20:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2011-03-06-jquery-themeswitchertool-working-version.html",
      "relativePath": "posts/2011-03-06-jquery-themeswitchertool-working-version.md",
      "key": "v-24cf8bc7",
      "path": "/posts/2011-03-06-jquery-themeswitchertool-working-version.html",
      "headers": [
        {
          "level": 3,
          "title": "Download",
          "slug": "download"
        },
        {
          "level": 3,
          "title": "Changes",
          "slug": "changes"
        },
        {
          "level": 3,
          "title": "Examples",
          "slug": "examples"
        },
        {
          "level": 3,
          "title": "Using Only Custom Themes",
          "slug": "using-only-custom-themes"
        },
        {
          "level": 3,
          "title": "New Options",
          "slug": "new-options"
        }
      ]
    },
    {
      "title": "How to Keep Your Linux Always-On In A Dual-Boot System",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "How to Keep Your Linux Always-On In A Dual-Boot System",
        "description": "Keeping nVidia loaded across boots",
        "excerpt": "Then came the hard part - how to make Fedora switch video drivers based on whther it boots in VirtualBox or not.",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "linux"
        ],
        "tags": [
          "Dual Boot",
          "nVidia",
          "CUDA"
        ],
        "created_at": "2012-02-04T08:10:00.000Z",
        "updated_at": "2020-09-01T01:29:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2012-02-04-how-to-keep-your-linux-always-on-in-a-dual-boot-system.html",
      "relativePath": "posts/2012-02-04-how-to-keep-your-linux-always-on-in-a-dual-boot-system.md",
      "key": "v-447503a7",
      "path": "/posts/2012-02-04-how-to-keep-your-linux-always-on-in-a-dual-boot-system.html",
      "headers": [
        {
          "level": 3,
          "title": "Update:",
          "slug": "update"
        }
      ]
    },
    {
      "title": "Inline input fields with minimal jQuery",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Inline input fields with minimal jQuery",
        "description": "Create an inline edit field with one line of jQuery",
        "excerpt": "Essentially one line of javascript to accomplish this easy feat",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development"
        ],
        "tags": [
          "jQuery"
        ],
        "created_at": "2012-05-25T14:46:00.000Z",
        "updated_at": "2012-05-25T14:46:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2012-05-25-inline-input-fields-with-mnimal-jquery.html",
      "relativePath": "posts/2012-05-25-inline-input-fields-with-mnimal-jquery.md",
      "key": "v-2e4394a7",
      "path": "/posts/2012-05-25-inline-input-fields-with-mnimal-jquery.html"
    },
    {
      "title": "Moved To Octopress!",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Moved To Octopress!",
        "description": "Rude Boy Solutions is now moving to Octopress",
        "excerpt": "Rude Boy Solutions is now moving to Octopress",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "personal"
        ],
        "tags": [
          "Rude Boy Solutions"
        ],
        "created_at": "2016-08-30T20:21:48.000Z",
        "updated_at": "2016-08-30T20:21:48.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2016-08-30-moved-to-octopress.html",
      "relativePath": "posts/2016-08-30-moved-to-octopress.md",
      "key": "v-2f1e7027",
      "path": "/posts/2016-08-30-moved-to-octopress.html",
      "headers": [
        {
          "level": 3,
          "title": "Rude Boy Solutions has Moved To Octopress!",
          "slug": "rude-boy-solutions-has-moved-to-octopress"
        }
      ]
    },
    {
      "title": "Data Migrations and You!",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Data Migrations and You!",
        "description": "Best Practices for Data Migrations",
        "excerpt": "Here was the chance to lose some old, bad habits, and replace them with new _Patterns_!",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "programming",
          "Ruby"
        ],
        "tags": [
          "best practices",
          "design patterns",
          "Rude Boy Solutions"
        ],
        "created_at": "2016-09-14T10:06:59.000Z",
        "updated_at": "2016-09-14T10:06:59.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2016-09-14-data-migrations-and-you.html",
      "relativePath": "posts/2016-09-14-data-migrations-and-you.md",
      "key": "v-57771753",
      "path": "/posts/2016-09-14-data-migrations-and-you.html",
      "headers": [
        {
          "level": 2,
          "title": "A Little Background",
          "slug": "a-little-background"
        },
        {
          "level": 2,
          "title": "Migrations Are Only For Modifying The Database",
          "slug": "migrations-are-only-for-modifying-the-database"
        },
        {
          "level": 3,
          "title": "Introducing Rails Runner",
          "slug": "introducing-rails-runner"
        },
        {
          "level": 3,
          "title": "Flow for Data Migrations",
          "slug": "flow-for-data-migrations"
        }
      ]
    },
    {
      "title": "All posts of Skaman Sam Tyler",
      "frontmatter": {
        "view": "posts",
        "title": "All posts of Skaman Sam Tyler",
        "excerpt": "Articles!",
        "lang": "en",
        "author": "skamansam"
      },
      "regularPath": "/posts/",
      "relativePath": "posts/README.md",
      "key": "v-5bb6e9e8",
      "path": "/posts/"
    },
    {
      "title": "How To Build a Dynamic Web Site With Simple Server Technologies.",
      "frontmatter": {
        "published": false,
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "How To Build a Dynamic Web Site With Simple Server Technologies.",
        "description": "Using SSI to build a more dynamic website",
        "excerpt": "In order to create a page that is easily maintainable, you need to do three",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development"
        ],
        "tags": [
          "SSI"
        ],
        "created_at": "2009-05-29T09:57:57.000Z",
        "updated_at": "2009-05-29T09:57:57.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/unpublished/2009-05-29-how-to-build-a-dynamic-web-site-with-simple-server-technologies.html",
      "relativePath": "unpublished/2009-05-29-how-to-build-a-dynamic-web-site-with-simple-server-technologies.md",
      "key": "v-032c5945",
      "path": "/unpublished/2009-05-29-how-to-build-a-dynamic-web-site-with-simple-server-technologies.html",
      "headers": [
        {
          "level": 2,
          "title": "Introduction",
          "slug": "introduction"
        },
        {
          "level": 2,
          "title": "Getting Started",
          "slug": "getting-started"
        },
        {
          "level": 2,
          "title": "The Setup",
          "slug": "the-setup"
        }
      ]
    },
    {
      "title": "Simple Rails Development Part II: Core GEdit Plugins",
      "frontmatter": {
        "published": false,
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Simple Rails Development Part II: Core GEdit Plugins",
        "description": "More Awesome GEdit Plugins for Ruby on Rails development",
        "excerpt": "In fact, there is an entire project devoted to just such a thing",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development"
        ],
        "tags": [
          "SSI"
        ],
        "created_at": "2012-08-31T22:44:51.000Z",
        "updated_at": "2012-08-31T22:44:51.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/unpublished/2012-08-31-simple-rails-development-part-ii-core-gedit-plugins.html",
      "relativePath": "unpublished/2012-08-31-simple-rails-development-part-ii-core-gedit-plugins.md",
      "key": "v-4feec42a",
      "path": "/unpublished/2012-08-31-simple-rails-development-part-ii-core-gedit-plugins.html"
    },
    {
      "title": "Dynamic Models in Rails 3",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Dynamic Models in Rails 3",
        "description": "How to create dynamic Models in Rails 3",
        "excerpt": "Rails 3 has a lot of nifty new features.",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "ruby"
        ],
        "tags": [
          "Ruby on Rails"
        ],
        "created_at": "2016-09-06T09:45:57.000Z",
        "updated_at": "2016-09-06T09:45:57.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/unpublished/2016-09-06-dynamic-models-in-rails-3.html",
      "relativePath": "unpublished/2016-09-06-dynamic-models-in-rails-3.md",
      "key": "v-5d2da6f1",
      "path": "/unpublished/2016-09-06-dynamic-models-in-rails-3.html"
    },
    {
      "title": "Firefox Add-Ons I can't Live Without",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Firefox Add-Ons I can't Live Without",
        "description": "Firefox Add-Ons I can't Live Without",
        "excerpt": "Since Firefox is the best browser so far (Google's Chrome a close second), here is a list of the best Firefox add-ons.",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "web-development"
        ],
        "tags": [
          "Browser Wars"
        ],
        "created_at": "2016-09-06T09:36:41.000Z",
        "updated_at": "2016-09-06T09:36:41.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/unpublished/2016-09-06-firefox-add-ons-i-cant-live-without.html",
      "relativePath": "unpublished/2016-09-06-firefox-add-ons-i-cant-live-without.md",
      "key": "v-780ca033",
      "path": "/unpublished/2016-09-06-firefox-add-ons-i-cant-live-without.html"
    },
    {
      "title": "Installing Amaya on Fedora 10 64bit",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Installing Amaya on Fedora 10 64bit",
        "description": "How to install the original web browser",
        "excerpt": "I prefer to test my web sites on as many browsers as possible",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "personal"
        ],
        "tags": [
          "Rude Boy Solutions"
        ],
        "created_at": "2016-09-06T09:34:28.000Z",
        "updated_at": "2016-09-06T09:34:28.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/unpublished/2016-09-06-installing-amaya-on-fedora-10-64bit.html",
      "relativePath": "unpublished/2016-09-06-installing-amaya-on-fedora-10-64bit.md",
      "key": "v-70a92b5f",
      "path": "/unpublished/2016-09-06-installing-amaya-on-fedora-10-64bit.html"
    },
    {
      "title": "Top Linux Apps I Can't Live Without",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Top Linux Apps I Can't Live Without",
        "description": "Awesome Linux apps you need to install from source",
        "excerpt": "[this article] outlines all the software Fedora or FreshRPMs does not have in their repos",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "linux"
        ],
        "tags": [
          "Fedora"
        ],
        "created_at": "2016-09-06T09:49:22.000Z",
        "updated_at": "2016-09-06T09:49:22.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/unpublished/2016-09-06-top-linux-apps-i-cant-live-without.html",
      "relativePath": "unpublished/2016-09-06-top-linux-apps-i-cant-live-without.md",
      "key": "v-7b888ce7",
      "path": "/unpublished/2016-09-06-top-linux-apps-i-cant-live-without.html"
    },
    {
      "title": "All unpublished posts of Skaman Sam Tyler",
      "frontmatter": {
        "view": "unpublished",
        "title": "All unpublished posts of Skaman Sam Tyler",
        "excerpt": "In Progress",
        "lang": "en",
        "author": "skamansam"
      },
      "regularPath": "/unpublished/",
      "relativePath": "unpublished/README.md",
      "key": "v-0f9630c8",
      "path": "/unpublished/"
    },
    {
      "title": "Simple Rails Development Part I: Gedit Click Config",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Simple Rails Development Part I: Gedit Click Config",
        "description": "Configuring GEdit Click Config Plugin",
        "excerpt": "I installed a few plugins, but only one of them took me by surprise\\: Click Config.",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "ruby"
        ],
        "tags": [
          "Ruby on Rails",
          "IDE"
        ],
        "created_at": "2012-08-30T23:29:00.000Z",
        "updated_at": "2012-08-30T23:29:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2012-08-30-simple-rails-development-part-i-gedit-click-config.html",
      "relativePath": "posts/2012-08-30-simple-rails-development-part-i-gedit-click-config.md",
      "key": "v-a7d683b2",
      "path": "/posts/2012-08-30-simple-rails-development-part-i-gedit-click-config.html",
      "headers": [
        {
          "level": 2,
          "title": "I Gotta Have It!",
          "slug": "i-gotta-have-it"
        },
        {
          "level": 2,
          "title": "You mentioned Ruby on Rails?",
          "slug": "you-mentioned-ruby-on-rails"
        },
        {
          "level": 2,
          "title": "Come Together",
          "slug": "come-together"
        }
      ]
    },
    {
      "title": "Building a unified time_select field",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Building a unified `time_select` field",
        "description": "Build a unified `time_select` field",
        "excerpt": "I was happy until the Rails upgrade caused my gem to inexplicably stop working.",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "ruby"
        ],
        "tags": [
          "Ruby on Rails"
        ],
        "created_at": "2013-04-10T11:10:11.000Z",
        "updated_at": "2013-04-10T11:10:11.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2013-04-10-building-a-unified-time-select-field.html",
      "relativePath": "posts/2013-04-10-building-a-unified-time-select-field.md",
      "key": "v-133acdb2",
      "path": "/posts/2013-04-10-building-a-unified-time-select-field.html"
    },
    {
      "title": "Cookie Detection in Rails 3",
      "frontmatter": {
        "comments": true,
        "view": "post",
        "layout": "post",
        "lang": "en",
        "author": "skamansam",
        "title": "Cookie Detection in Rails 3",
        "description": "How to detect cookies in Rails 3",
        "excerpt": "I believe this may be a bad idea, in general, but here is a cheap way",
        "cover": false,
        "coverImage": false,
        "coverAlt": "RBE Logo",
        "categories": [
          "ruby"
        ],
        "tags": [
          "Ruby on Rails"
        ],
        "created_at": "2013-04-23T17:14:12.000Z",
        "updated_at": "2016-08-30T00:00:00.000Z",
        "meta": [
          {
            "property": "og:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          },
          {
            "name": "twitter:image",
            "content": "/images/GSoC-logo-horizontal-800.png"
          }
        ]
      },
      "regularPath": "/posts/2013-04-23-cookie-detection-in-rails-3.html",
      "relativePath": "posts/2013-04-23-cookie-detection-in-rails-3.md",
      "key": "v-76afa00a",
      "path": "/posts/2013-04-23-cookie-detection-in-rails-3.html"
    }
  ],
  "themeConfig": {
    "locales": {
      "/": {
        "languages": {
          "label": "English",
          "shortname": "EN"
        },
        "translation": {
          "news_title": "Receive our articles, videos and more directly in your inbox and stay up to date."
        },
        "ads": [],
        "logo": {
          "name": "rbe_logo",
          "ext": "gif",
          "alt": "RBE Logo: The Machine"
        },
        "share": {
          "facebookCaption": "",
          "twitterVia": ""
        },
        "newsletter": {
          "provider": "mailchimp",
          "action": ""
        },
        "copy": "2020 © Rude Boy Enterprises - \n        <a href=\"https://vuepress.vuejs.org/\" rel=\"noopener\" target=\"_blank\">\n          MADE WITH VUEPRESS\n        </a>",
        "footer": {
          "nav1": {
            "title": "Rude Boy Enterprises",
            "items": [
              {
                "label": "ABOUT",
                "path": "/about/"
              },
              {
                "label": "CATEGORIES",
                "path": "/categories/"
              },
              {
                "label": "CONTACT",
                "path": "/contact/"
              }
            ]
          },
          "nav2": {
            "title": "Community",
            "items": []
          }
        },
        "social": []
      }
    },
    "serviceWorker": {
      "updatePopup": {
        "message": "New content 🎉🎉",
        "buttonText": "Update"
      }
    },
    "disqus": "rubeboyenterprises",
    "url": "https://rudeboy.dev",
    "cdn": "",
    "blackWhite": true,
    "topNavigation": false,
    "searchMaxSuggestions": 7,
    "responsive": {
      "active": true,
      "ext": "png",
      "breakpoints": []
    },
    "lazyLoad": {},
    "share": {
      "facebook": {
        "appId": "310554869041836",
        "version": "v3.1"
      }
    },
    "elevator": {
      "duration": 4000,
      "mainAudio": "/music/goingup.mp3",
      "endAudio": "/music/ding.mp3"
    }
  },
  "locales": {
    "/": {
      "lang": "en",
      "path": "/"
    }
  }
}