module.exports = {
  content: ['./src/**/*.{html,js,svelte,ts,md,mdx,mds}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        tertiary: 'var(--color-tertiary)',
        quaternary: 'var(--color-quaternary)',
        secondarySoft: 'var(--color-secondarySoft)',
        secondaryBg: 'var(--color-secondaryBg)',
        primaryBorder: 'var(--color-primaryBorder)',
        primarySoft: 'var(--color-primarySoft)',
        primaryBold: 'var(--color-primaryBold)',
        primaryBg: 'var(--color-primaryBg)',
        primaryBgSoft: 'var(--color-primaryBgSoft)',
        primaryBgSofter: 'var(--color-primaryBgSofter)',
        onPrimaryBg: 'var(--color-onPrimaryBg)',
        onPrimaryBgSoft: 'var(--color-onPrimaryBgSoft)',
        onPrimaryBgSofter: 'var(--color-onPrimaryBgSofter)',
        onSecondaryBg: 'var(--color-onSecondaryBg)',
        tertiaryBg: 'var(--color-tertiaryBg)',
        onTertiaryBg: 'var(--color-onTertiaryBg)',
        linkColor: 'var(--color-linkColor)',
        neutralBg: 'var(--color-neutralBg)',
        neutralBgSoft: 'var(--color-neutralBgSoft)',
        neutralBgSofter: 'var(--color-neutralBgSofter)',
        neutral: 'var(--color-neutral)',
        neutralBold: 'var(--color-neutralBold)',
        neutralSoft: 'var(--color-neutralSoft)',
        onNeutralBg: 'var(--color-onNeutralBg)',
        onNeutralBgSoft: 'var(--color-onNeutralBgSoft)',
        onNeutralBgSofter: 'var(--color-onNeutralBgSofter)',
      },
      borderRadius: {
        'none': 'var(--border-radius-none, 0)',
        'sm': 'var(--border-radius-small, .125rem)',
        DEFAULT: 'var(--border-radius, .25rem)',
        'md': 'var(--border-radius-md, .375rem)',
        'lg': 'var(--border-radius-lg, .5rem)',
        'xl': 'var(--border-radius-xl, .75rem)',
        '2xl': 'var(--border-radius-2xl, 1rem)',
        '3xl': 'var(--border-radius-3xl, 1.5rem)',
        '4xl': 'var(--border-radius-4xl, 2rem)',
        '5xl': 'var(--border-radius-5xl, 2.5rem)',
        '6xl': 'var(--border-radius-6xl, 3rem)',
        'full': 'var(--border-radius-full, 9999px)',
        'element': 'var(--border-radius-element, var(--border-radius, .25rem))',
      },
      dropShadow: {
        'element': 'var(--drop-shadow-element)',
      },
      width: {
        'md': 'var(--width-md, 768px)',
      }
    },
    fontFamily: {
      logoFont: 'var(--font-logoFont)',
    },

  },
  plugins: [],
}
