name: Deploy to `main`

on:
  push:
    branches: [ "svelte" ]
  pull_request:
    branches: [ "svelte" ]

  # Allows you to run this workflow manually from the Actions tab
  #   workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm i
      - name: Deploy
        run: |
          git config init.defaultBranch main
          git config user.email "skamansam@users.noreply.github.com"
          git config user.name "Github Deploy Action"
          pnpm deploy