name: Deploy to `main`

on:
  push:
    branches: [ "svelte" ]
  pull_request:
    branches: [ "svelte" ]

  # Allows you to run this workflow manually from the Actions tab
  #   workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm i
      - name: Build
        run: | 
          rm -rf build
          pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
#       - name: Deploy
#         run: |
#           # git config --global init.defaultBranch main
#           # mkdir -p build
#           # cd build
#           # git init 
#           git config --global user.email github-actions@github.com
#           git config --global user.name github-actions
#           # pnpm build
#           mv build docs
#           touch docs/.nojekyll
#           git add -f docs/*
#           git commit -m "deploy"
#           git push 
#           # -f https://github.com/skamansam/skamansam.github.io.git main
